:hammer: fix: responsivity error in the anouncemment image
Error: Anouncemment image was very big when  high screen size

Cause: That was no limit to the anouncemment image weight and height